jobs:
  include:
    - language: python
      python: 3.8
      script:
      - pytest testing.py

    - language: node_js
      node_js: 12
      script:
      - node -e "console.log('Hi from NodeJS!')"


