jobs:
  include:
    - language: python
      python: 3.8
      services:
      - mongodb
      install: 
      - pip install Flask
      - pip install flask-unittest
      - pip install flask_cors
      - pip install pymongo
      - pip install codecov
      before_script:
      - sleep 15
      - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
      script:
      - pytest ./backend/testing.py
      after_success:
      - codecov

    - language: node_js
      node_js: 12
      script:
      - node -e "console.log('Hi from NodeJS!')"
