jobs:
  include:
    - language: python
      python: 3.8
      install: 
      - pip install Flask
      script:
      - pytest ./backend/testing.py

    - language: node_js
      node_js: 12
      script:
      - node -e "console.log('Hi from NodeJS!')"


